M48
; DRILL file {KiCad 9.0.5} date 2025-11-11T22:55:29+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-11T22:55:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X113.54Y-84.2
X113.54Y-99.2
T2
X103.5Y-47.5
X103.5Y-96.5
X161.5Y-47.5
X161.5Y-96.5
M30
